import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Modal1 from "./components/Modal1";
import Modal2 from "./components/Modal2";

const Home: NextPage = () => {
  return (
    <div className="overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Modal1 />

      <Modal2 />
    </div>
  );
};

export default Home;
